### ISSUE TITLE
Beta21 Telegram Desktop App does not accept clicks via Touchscreen

### ISSUE THREAD

**Issue by angelo6479** [manjaro-pinephone/phosh#25]
I've installed Telegram Desktop via Software in Beta 21.
But I cant access it via Touch, Keyboard is working.
Same Problem in Neochat.

Do I need some additional configuration _

Angelo

**Comment by philmmanjaro** [comment]
that is one of the reasons we dropped those apps to be supported for now.

**Comment by angelo6479** [comment]
Ok, thx for the fast reply
