### ISSUE TITLE
NetworkManager not running

### ISSUE THREAD

**Issue by Connie-Fur** [manjaro-pinephone/phosh#26]
I installed beta21 on a brand new (i.e. clean) 32GB micro-sd card. On going to Settings then Network I get an
"Oops, something has gone wrong" etc message with "NetworkManager needs to be running."

**Comment by robster7674** [comment]
Just had the same issue after installing beta22 on PinePhone, internal storage, not sd.

**Comment by philmmanjaro** [comment]
![image](https://user-images.githubusercontent.com/5050022/153853714-3433b9eb-caf4-4ff9-86c5-1ee899cd9456.png)
works fine on my end after a reboot ...

**Comment by robster7674** [comment]
For me too: after a reboot it works ok. I remembered that before I went into Settings after logging in, I toggled Wi-Fi from the top menu. Perhaps that's related?

**Comment by philmmanjaro** [comment]
Happens sometimes when the Modem is funky. Mostly a restart resets it.

**Comment by Connie-Fur** [comment]
Thanks guys. A reboot fixed mine too.
As an aside, just after sending the last post I noticed it was telling me it couldn't find a cellular modem either. A battery-out reboot fixed that too.
So thanks again.
