### ISSUE TITLE
Copy/paste from Terminal not working

### ISSUE THREAD

**Issue by robster7674** [manjaro-pinephone/phosh#29]
When I tried Ctrl+C to copy text in Terminal, it does not seem to work. Ctrl+V after that does not result in anything being pasted. Long press brings up a menu with Paste and Select All, but no Copy.

How do I copy/paste text in Terminal (this is the default terminal app)?

**Comment by robster7674** [comment]
Trying Ctrl+Shift+V gives me ^C at the prompt, as if only Ctrl+C is pressed.

**Comment by robster7674** [comment]
Continuing discussion in https://gitlab.gnome.org/GNOME/console/-/issues/88.

**Comment by philmmanjaro** [comment]
well it is not gnome-console used here. rather this: https://gitlab.gnome.org/ZanderBrown/kgx/

**Comment by robster7674** [comment]
Thanks, but going to that link redirects to console, and displays:
```
 Project 'ZanderBrown/kgx' was moved to 'GNOME/console'. Please update any links and bookmarks that may still have the old path.
```
