### ISSUE TITLE
Battery input_current_limit too low on Pinephone Pro - POSH and Plasma

### ISSUE THREAD

**Issue by joeg1484** [manjaro-pinephone/phosh#34]
Hi All,
I got my new Pinephone Pro and started to charge it as I was supposed to. I set it on and came back 3 hrs later and it was just below 26% charged. This was strange, so I got on the Discord channel for the Pinephone and did some troubleshooting and determined that the following setting is way too low:
/sys/class/power_supply/rk818-usb/input_current_limit

Default its 450000
``` 
[manjaro@manjaro-arm ~]$ cat /sys/class/power_supply/rk818-usb/input_current_limit
450000
```

I was told to change that to 1500000 and this caused my battery to charge at a normal rate.

However, this gets set back to the default every time I plug/unplug the usb cable.

Can we get this changed and set as default in the distro. Also, is there a work around for this for now, something like a udev rule or something along those lines?

Im using the latest version of Manjaro for the Pinephone Pro for both POSH and Plasma - its happens on both.

Let me know if you need more info.
Thanks!
Joe

**Comment by adamfowleruk** [comment]
This seems to be set to 2000000 on the latest 20220925 nightly build if that helps @joeg1484.

**Comment by joeg1484** [comment]
Hi Adam,
Thanks for the follow up on this... Is this something I can get during an update, or do I have to re-flash with the version you mentioned? Or, perhaps go to a testing repo?

Thanks again!
Joe

**Comment by joeg1484** [comment]
Oh, nevermind. I just did an update and plugged in and see the change

`cat /sys/class/power_supply/rk818-usb/input_current_limit
2000000`

Thanks again!
