### ISSUE TITLE
Loads to a Login Prompt

### ISSUE THREAD

**Issue by fdservices** [manjaro-pinephone/phosh#6]
Downloaded the latest image and burnt it to an SD card without any apparent problem.

When I restart the Pinephone I see the logo, followed by a login prompt. I cannot log in on the phone at this point, so I cannot proceed.

**Comment by philmmanjaro** [comment]
Wait until resizing of **first boot** finished, it will login to **phosh** automatically.

**Comment by fdservices** [comment]
For information, how long can this take .... I waited for an hour or so.
