### ISSUE TITLE
Megapixels was working on Beta 27 but after an update it stopped working on PPP

### ISSUE THREAD

**Issue by jsarkari** [manjaro-pinephone/phosh#60]
So I installed Beta 27 phosh on PPP, tested Megapixels and it worked yesterday and took my first photos (albeit a 6 month wait) -:)

So I applied an update and tested Megapixels again and it will not open again.

So I ran via terminal and noticed some errors now, not sure if there were some changes which has affected the camera app.

See attached photos of running the app via terminal and the results.

There is 1 warning and 8 errors.

The errors mainly relate to error 22, Invalid argument I am presuming in the .ini file in the config folder.
![PXL_20221105_103055499](https://user-images.githubusercontent.com/18397011/200116123-2a8b78d3-b0ef-4eff-86a6-9894e5e0bb31.jpg)
![PXL_20221105_103114033](https://user-images.githubusercontent.com/18397011/200116126-0a1c51b2-4c20-4a63-981d-c6cbdecdf6ea.jpg)

**Comment by philmmanjaro** [comment]
well, I wrote the reason in the change log of development:

We updated the kernel to [6.0.2](https://github.com/megous/linux/releases/tag/orange-pi-6.0-20221017-0205)
- V4L2 apparently doesn’t have as strict backwards compatibility guarantees, and mainline changed the media graph for Rockchip ISPs, hence Megapixels support on PPP for cameras doesn’t work anymore
