### ISSUE TITLE
Firefox 108.0.1-1 - unresponsive on touching the page rendering area

### ISSUE THREAD

**Issue by mouffa** [manjaro-pinephone/phosh#66]
can not click or scroll on the rendering area, it is only possible to click the navigation toolbar buttons or navigate with the keyboard, 

if launched from the terminal gives the following output,

`Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: cannot access /sys/bus/pci (t=2.52382) [GFX1-]: glxtest: cannot access /sys/bus/pci`

`Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: cannot access /sys/bus/pci (t=2.52382) |[1][GFX1-]: glxtest: DRM render node not clearly detectable. Falling back to using the only one that was found. (t=2.52428) [GFX1-]: glxtest: DRM render node not clearly detectable. Falling back to using the only one that was found.`

`Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: cannot access /sys/bus/pci (t=2.52382) |[1][GFX1-]: glxtest: DRM render node not clearly detectable. Falling back to using the only one that was found. (t=2.52428) |[2][GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection. (t=2.52436) [GFX1-]: glxtest: VA-API test failed: failed to initialise VAAPI connection.`

`dmesg` doesn't output anything

`journalctl -f` only complains about ALSA

`manjaro-arm firefox.desktop : ALSA lib seq_hw.c:466 (snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory`

why is it trying to access the PCI ?

is there a PCI bus on the phone ? 

at least the A64 has no PCI except if the name is used for another bus, I don't even know if those errors have something to do with the problem or it is some configuration problem with the `mobile-config-firefox` package

**Comment by pjsfx** [comment]
I have the same issue, oddly if you rotate the screen into landscape input works fine.

**Comment by mouffa** [comment]
@pjsfx this bug has already been reported in the PostmarketOS source repository which may be the same source for the Manjaro package

https://gitlab.com/postmarketOS/mobile-config-firefox/-/issues/48

**Comment by mouffa** [comment]
@pjsfx the Manjaro source is here

https://gitlab.manjaro.org/manjaro-arm/packages/community/phosh/mobile-config-firefox

**Comment by mouffa** [comment]
I fixed it  by commenting out a previous fix, in file `/etc/mobile-config-firefox/userChrome.css` I commented out the `#mainPopupSet` section, lines 167 -173

**Comment by mouffa** [comment]
@pjsfx you can apply the fix I did, I followed the advice of that PostmarketOS comment and I commented out the fix for the flickering tabs, the other option was to comment out the section which moves the toolbar at the bottom

the disadvantage of the option I chose is that the popups for the certificates etc are not displayed properly

 but it seems that `108.0.2-1` works well without a fix at least on this image 

https://github.com/dreemurrs-embedded/Pine64-Arch

so after your Firefox is updated again try to uncomment the fix to see if it works so that you don't have unnecessary tweaks in your system

I reckon that if the `mobile-config-firefox` is updated at some point whatever intervention you have done will be lost as those files will be overwritten
